### ISSUE TITLE
Implement Basic `GitHub Actions` Workflows

### ISSUE THREAD

**Issue by xKabbe** [xKabbe/astrolens#29]
### Description

Given the current structure of the project, we probably need multiple workflow files to use `GitHub Actions` for our frontend, backend, docker, e2e testing, documentation, linting, test coverage and more.

Identify which use cases could be helpful in the future and create workflows with basic content. Follow-up issues can be created to add the real content to these workflows.

### Additional Context

None

### Expected Actions

- [ ] Identified a group of use cases and created workflow files with basic content (also created follow-up issues for these workflows)

### Definition Of Done

- [ ] Code implemented
- [ ] Tests implemented and passing
- [ ] Documentation implemented
- [ ] GitHub Actions are passing
